---
- name: Wait for webpage to serve content
  uri:
    url: "{{control_center_http_protocol}}://{{inventory_hostname}}:{{control_center_port}}"
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 40
  delay: 10
  when: not rbac_enabled|bool and not control_center_ssl_mutual_auth_enabled|bool

- name: Wait for webpage to serve content - mTLS
  uri:
    url: "{{control_center_http_protocol}}://{{inventory_hostname}}:{{control_center_port}}"
    validate_certs: false
    client_cert: "{{control_center_cert_path}}"
    client_key: "{{control_center_key_path}}"
  register: result
  until: result.status == 200
  retries: 40
  delay: 10
  when: not rbac_enabled|bool and control_center_ssl_mutual_auth_enabled|bool

- name: Wait for webpage to serve content - RBAC
  uri:
    url: "{{control_center_http_protocol}}://{{inventory_hostname}}:{{control_center_port}}"
    validate_certs: false
    url_username: "{{control_center_ldap_user}}"
    url_password: "{{control_center_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 40
  delay: 10
  when: rbac_enabled|bool and not control_center_ssl_mutual_auth_enabled|bool

- name: Wait for webpage to serve content - RBAC - mTLS
  uri:
    url: "{{control_center_http_protocol}}://{{inventory_hostname}}:{{control_center_port}}"
    validate_certs: false
    client_cert: "{{control_center_cert_path}}"
    client_key: "{{control_center_key_path}}"
    url_username: "{{control_center_ldap_user}}"
    url_password: "{{control_center_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 40
  delay: 10
  when: rbac_enabled|bool and control_center_ssl_mutual_auth_enabled|bool
