---
- name: Check if kafka rest Service Running
  shell: "systemctl show -p SubState {{kafka_rest_service_name}}"
  changed_when: false
  register: substate

- name: Parallel Restart
  include: restart.yml
  when: substate.stdout != 'SubState=running'

# All kafka rest hosts iterate over the list of kafka rest hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match  the entry in the loop
# restart.yml tasks will only run for that host ON that host
- name: Serial Restart
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups['kafka_rest'] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
    - substate.stdout == 'SubState=running'
