---
- name: Get Kafka Cluster ID from Zookeeper
  shell: /usr/bin/zookeeper-shell localhost:2181 get /cluster/id | grep version
  delegate_to: "{{ groups['zookeeper'][0] }}"
  register: cluster_id_query

- set_fact:
    cluster_id_json: "{{ cluster_id_query.stdout }}"

- name: Set kafka_cluster_id Variable
  set_fact:
    kafka_cluster_id: "{{ cluster_id_json.id }}"

- name: Create SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755

- name: Copy in MDS Public Pem File
  copy:
    src: "{{token_services_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: '755'
    owner: "{{user}}"
    group: "{{group}}"
