---
- name: Get Package Facts
  package_facts:
    manager: auto

- set_fact:
    confluent_server_enabled: true
  when: ansible_facts.packages['confluent-server'] is defined

- set_fact:
    confluent_server_enabled: false
  when: ansible_facts.packages['confluent-kafka-2.12'] is defined
