---
- name: RBAC Setup Tasks
  include_tasks: ../../tasks/rbac_setup.yml
  vars:
    user: "{{ksql_user}}"
    group: "{{ksql_group}}"

- name: Grant role System Admin to Additional KSQL Super Users
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/security/1.0/principals/User:{{item}}/roles/SystemAdmin"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "clusters": {
          "kafka-cluster": "{{kafka_cluster_id}}",
          "ksql-cluster": "{{ksql.properties['ksql.service.id']}}"
        }
      }
    status_code: 204
  loop: "{{ksql_additional_system_admins}}"

- name: Grant ResourceOwner of KSQL Cluster on KSQL User
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "ksql-cluster":"{{ksql.properties['ksql.service.id']}}"
          }
        },
        "resourcePatterns": [{
          "resourceType": "KsqlCluster",
          "name": "ksql-cluster"
        }]
      }
    status_code: 204

- name: Grant ksql user the ResourceOwner role with three resourcePatterns
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
          }
        },
        "resourcePatterns": [
          {
            "resourceType": "Topic",
            "name": "_confluent-ksql-{{ksql.properties['ksql.service.id']}}_command_topic",
            "patternType":"LITERAL"
          },
          {
            "resourceType":"Topic",
            "name":"{{ksql.properties['ksql.service.id']}}-ksql_processing_log",
            "patternType":"LITERAL"
          },
          {
            "resourceType":"Group",
            "name":"_confluent-ksql-{{ksql.properties['ksql.service.id']}}",
            "patternType":"PREFIXED"
          }
        ]
      }
    status_code: 204

- name: Grant ksql user the DeveloperWrite role on resourceType TransactionalId
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/DeveloperWrite/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
          }
        },
        "resourcePatterns": [{
          "resourceType": "TransactionalId",
          "name": "{{ksql.properties['ksql.service.id']}}",
          "patternType":"LITERAL"
        }]
      }
    status_code: 204

# TODO find a way to get around hardcoding this sr cluster id
- name: Grant ksql user the DeveloperRead role on resourceType Subject in Schema Registry Cluster
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/DeveloperRead/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "schema-registry-cluster":"schema-registry"
          }
        },
        "resourcePatterns": [{
          "resourceType": "Subject",
          "name": "_confluent-ksql-{{ksql.properties['ksql.service.id']}}",
          "patternType":"PREFIXED"
        }]
      }
    status_code: 204
  when: "'schema_registry' in groups"
