---
- name: Restart KSQL Service
  systemd:
    daemon_reload: true
    name: "{{ksql_service_name}}"
    state: restarted

- name: Health Check
  include: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
