---
- name: Check if KSQL Service Running
  shell: "systemctl show -p SubState {{ksql_service_name}}"
  changed_when: false
  register: substate

- name: Parallel Restart
  include: restart.yml
  when: substate.stdout != 'SubState=running'

# All ksl hosts iterate over the list of ksql hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match  the entry in the loop
# restart.yml tasks will only run for that host ON that host
- name: Serial Restart
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups['ksql'] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
    - substate.stdout == 'SubState=running'
