---
# More kafka_rest variables are defined in the confluent.variables role

### Boolean to enable cp-ansible's Custom Log4j Configuration
kafka_rest_custom_log4j: "{{ custom_log4j }}"

kafka_rest_java_args:
  - "{% if kafka_rest_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if kafka_rest_jolokia_enabled|bool %}-javaagent:{{jolokia_jar_path}}=port={{kafka_rest_jolokia_port}},host=0.0.0.0{% if kafka_rest_jolokia_ssl_enabled|bool %},keystore={{kafka_rest_keystore_path}},keystorePassword={{kafka_rest_keystore_storepass}},protocol=https{% endif %}{% endif %}"
  - "{% if kafka_rest_custom_log4j|bool %}-Dlog4j.configuration=file:{{kafka_rest.log4j_file}}{% endif %}"
  - "{% if kafka_rest_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{kafka_rest_jmxexporter_port}}:{{kafka_rest_jmxexporter_config_path}}{% endif %}"

### Custom Java Args to add to the Rest Proxy Process
kafka_rest_custom_java_args: ""

kafka_rest_final_java_args: "{{ kafka_rest_java_args + [ kafka_rest_custom_java_args ] }}"

# Key/Value Pairs with empty values will not be written into override.conf
kafka_rest_service_overrides:
  User: "{{ kafka_rest_user if kafka_rest_user != kafka_rest_default_user else '' }}"
  Group: "{{ kafka_rest_group if kafka_rest_group != kafka_rest_default_group else '' }}"

kafka_rest_service_environment_overrides:
  LOG_DIR: /var/log/kafka-rest
  KAFKAREST_OPTS: "{{ kafka_rest_final_java_args | java_arg_build_out }}"

kafka_rest:
  appender_log_path: /var/log/rest-proxy/
  appender_log_name: rest-proxy.log
  appender_max_log_files: 10
  appender_log_file_size: 100MB
