---
- name: Get Leader/Follower
  shell: "{{zookeeper_health_check_command}} | grep Mode"
  args:
    executable: /bin/bash
  register: leader_query
  changed_when: false
  check_mode: false

# All zookeeper hosts iterate over the list of zookeeper hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match  the entry in the loop
# restart.yml tasks will only run for that host ON that host
- name: Restart Followers
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups['zookeeper'] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
    # Edge case that zk is in standalone mode (ie only one node)
    - '"follower" in leader_query.stdout or "standalone" in leader_query.stdout'

- name: Restart Leader
  include: restart.yml
  delegate_to: "{{ inventory_hostname }}"
  when: '"leader" in leader_query.stdout'
