---
# More control_center variables are defined in the confluent.variables role

### Boolean to enable cp-ansible's Custom Log4j Configuration
control_center_custom_log4j: "{{ custom_log4j }}"

control_center_java_args:
  - "{% if control_center_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"

### Custom Java Args to add to the Control Center Process
control_center_custom_java_args: ""

control_center_final_java_args: "{{ control_center_java_args + [ control_center_custom_java_args ] }}"

### Full Path to the RocksDB Data Directory. If left as empty string, cp-ansible will not configure RocksDB
control_center_rocksdb_path: ""

# Empty values will not be written into override.conf
control_center_service_overrides:
  User: "{{ control_center_user if control_center_user != control_center_default_user else '' }}"
  Group: "{{ control_center_group if control_center_group != control_center_default_group else '' }}"

control_center_service_environment_overrides:
  ROCKSDB_SHAREDLIB_DIR: "{{control_center_rocksdb_path}}"
  CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"
  CONTROL_CENTER_OPTS: "{{ control_center_final_java_args | java_arg_build_out }}"
  CONTROL_CENTER_LOG4J_OPTS: "{% if control_center_custom_log4j|bool %}-Dlog4j.configuration=file:{{control_center.log4j_file}}{% endif %}"

control_center:
  appender_log_path: /var/log/confluent/control-center/
  c3appender_log_name: control-center.log
  c3appender_max_log_files: 10
  c3appender_log_file_size: 100MB
  streamsappender_log_name: control-center-streams.log
  streamsappender_max_log_files: 10
  streamsappender_log_file_size: 100MB
  kafkaappender_log_name: control-center-kafka.log
  kafkaappender_max_log_files: 10
  kafkaappender_log_file_size: 100MB
