---
# More ksql variables are defined in the confluent.variables role

### Boolean to enable cp-ansible's Custom Log4j Configuration
ksql_custom_log4j: "{{ custom_log4j }}"

ksql_java_args:
  - "{% if ksql_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if ksql_jolokia_enabled|bool %}-javaagent:{{jolokia_jar_path}}=port={{ksql_jolokia_port}},host=0.0.0.0{% if ksql_jolokia_ssl_enabled|bool %},keystore={{ksql_keystore_path}},keystorePassword={{ksql_keystore_storepass}},protocol=https{% endif %}{% endif %}"
  - "{% if ksql_custom_log4j|bool %}-Dlog4j.configuration=file:{{ksql.log4j_file}}{% endif %}"
  - "{% if ksql_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{ksql_jmxexporter_port}}:{{ksql_jmxexporter_config_path}}{% endif %}"

### Custom Java Args to add to the ksqlDB Process
ksql_custom_java_args: ""

ksql_final_java_args: "{{ ksql_java_args + [ ksql_custom_java_args ] }}"

# Key/Value Pairs with empty values will not be written into override.conf
ksql_service_overrides:
  LimitNOFILE: 100000
  User: "{{ ksql_user if ksql_user != ksql_default_user else '' }}"
  Group: "{{ ksql_group if ksql_group != ksql_default_group else '' }}"

ksql_service_environment_overrides:
  KSQL_HEAP_OPTS: "-Xmx3g"
  KSQL_OPTS: "{{ ksql_final_java_args | java_arg_build_out }}"

ksql:
  appender_log_path: /var/log/confluent/ksql/
  appender_log_name: ksql.log
  appender_max_log_files: 10
  appender_log_file_size: 100MB
  streams_appender_log_name: ksql-streams.log
  streams_appender_max_log_files: 10
  streams_appender_log_file_size: 100MB
  kafka_appender_log_name: ksql-kafka.log
  kafka_appender_max_log_files: 10
  kafka_appender_log_file_size: 100MB
