---
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - name: Check 2 way tls line omitted in properties
      shell: |
        grep "confluent.metadata.server.ssl.truststore.location"  /etc/kafka/server.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 1

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090


- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090
