---
- name: Kafka Broker - Host Ordering
  hosts: kafka_broker
  # Running serial=1 because add_host has problems
  # https://stackoverflow.com/questions/42106527/ansible-how-to-call-module-add-host-for-all-hosts-of-the-play
  serial: 1
  tasks:
    - name: Set confluent_server_enabled and kafka_broker_jolokia_ssl_enabled Variables
      include_tasks: tasks/set_kafka_broker_jolokia_ssl_enabled.yml
    - name: Create Ordered Kafka Broker Groups
      import_tasks: tasks/create_ordered_kafka_groups.yml
      vars:
        controller_group: controller
        non_controller_group: non_controllers
- name: Kafka Broker Provisioning
  serial: 1
  hosts: non_controllers
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_broker
- name: Kafka Broker Provisioning
  hosts: controllers
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_broker
