---
- name: Copy the client configuration file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
  when: kerberos_configure|bool

- name: Create Keytabs Directory
  file:
    path: "{{ kerberos_keytab_destination_path | dirname }}"
    state: directory
    group: "{{kerberos_group}}"
    mode: '650'

- name: Copy in Keytab File
  copy:
    src: "{{kerberos_keytab_path}}"
    dest: "{{kerberos_keytab_destination_path}}"
    owner: "{{kerberos_user}}"
    group: "{{kerberos_group}}"
    mode: '600'
  notify: "{{kerberos_handler}}"
