---
- name: Restart Schema Registry Service
  systemd:
    daemon_reload: true
    name: "{{schema_registry_service_name}}"
    state: restarted

- name: Health Check
  include: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
