---
# Restart/start SR hosts serially because there is a race condition on topic creation when multiple hosts start at the same time

# All schema registry hosts iterate over the list of schema registry hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match  the entry in the loop
# restart.yml tasks will only run for that host ON that host
- name: Serial Restart
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups['schema_registry'] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
