---
- name: Restart Zookeeper Service
  systemd:
    daemon_reload: true
    name: "{{zookeeper_service_name}}"
    state: restarted

- name: Zookeeper Health Check
  include: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
