---
- name: Gather OS Facts
  setup:
    # Only gathers ansible_distribution_release, filters out the rest
    filter: ansible_distribution_release
    gather_subset:
      - '!all'

- name: Install apt-transport-https
  shell: apt-get install apt-transport-https -y --force-yes
  args:
    warn: false

- name: Add Confluent Apt Key
  apt_key:
    url: "{{confluent_common_repository_debian_key_url}}"
    state: present
  when: not custom_apt_repo|bool

- name: Add Confluent Apt Repo
  apt_repository:
    repo: "{{confluent_common_repository_debian_repository}}"
    state: present
  register: apt_add_result
  until: apt_add_result is success
  retries: 10
  delay: 5
  when: not custom_apt_repo|bool

- name: Add Custom Apt Repo
  copy:
    src: "{{custom_apt_repo_filepath}}"
    dest: /etc/apt/sources.list.d/custom_confluent.list
  when: custom_apt_repo|bool
  notify:
    - apt-get update

- meta: flush_handlers

- name: Copy in repo skip valid check
  copy:
    content: 'Acquire::Check-Valid-Until "0";'
    dest: /etc/apt/apt.conf.d/skip-check
  notify:
    - debian apt-get update
  when:
    - install_java|bool
    - not custom_apt_repo|bool

- name: Add jessie-backports Repo
  lineinfile:
    path: /etc/apt/sources.list
    line: deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main
    regexp: '.*jessie-backports.*'
  notify:
    - debian apt-get update
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "jessie"

- name: Add stretch-backports Repo
  lineinfile:
    path: /etc/apt/sources.list
    line: deb [check-valid-until=no] http://ftp.debian.org/debian stretch-backports main
    regexp: '.*stretch-backports.*'
  notify:
    - debian apt-get update
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "stretch"

- meta: flush_handlers

- name: Install Java - jessie
  apt:
    name: "{{ debian_java_package_name }}"
    state: present
    default_release: jessie-backports
  register: java_install_result
  until: java_install_result is success
  retries: 10
  delay: 5
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "jessie"

- name: Install Java - stretch
  apt:
    name: "{{ debian_java_package_name }}"
    state: present
    default_release: stretch-backports
  register: java_install_result
  until: java_install_result is success
  retries: 10
  delay: 5
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "stretch"

- name: Install Java (Custom Repo)
  apt:
    name: "{{ debian_java_package_name }}"
    state: present
  register: java_install_result
  until: java_install_result is success
  retries: 10
  delay: 5
  when:
    - install_java|bool
    - custom_apt_repo|bool

- name: Install rsync, ca-certificates, openssl, unzip
  apt:
    name: "{{ item }}"
  loop:
    - rsync
    - ca-certificates
    - openssl
    - unzip
    - curl
